### PR TITLE
fixed some issues

### PR DESCRIPTION
**Pull request by marcosprosperiOrigin**
fix somes errores, move folder does not delete in ios, fix param name in permant delete, fixed how to get headers in getmails and getmail

### CODE REVIEW

**Comment by fdeprezOrigin** [comment]
Hey @agenthunt did you have time to review this?

Thanks!

**Comment by agenthunt** [comment]
Thanks @marcosprosperiOrigin @fdeprezOrigin . I haven't had time to look into it yet. But looks like there are some conflicts. I was actually thinking of setting up automated builds before other pull request, but you guys are super fast :)

**Comment by agenthunt** [comment]
Hi @marcosprosperiOrigin , @fdeprezOrigin ,
Just finished setting Github actions to  build BasicExample for every commit pushed. Please merge the latest from upstream and update your PR. We should be seeing an automated build kicked off. Going further , we can expand it to run some tests as well. 
Thanks.

**Comment by agenthunt** [comment]
Thanks @marcosprosperiOrigin . Yay. The Android CI Build is working.  Please let me know if there are more fixes coming in? We probably have to start making a Release Notes and Change log :)

**Pull request merged**
