### PR TITLE
Single attachment in Android

### PR DESCRIPTION
**Pull request by plastbox**
Added preliminary support for single attachment on Android.

### CODE REVIEW

**Comment by agenthunt** [comment]
Hi @plastbox , Thanks for the PR. Could you please update the BasicExample with this usage ? 
Could you please update README with code snippet ?
Also Are you planning to update it for iOS as well? If not could you add that to the README as well

**Comment by maxaggedon** [comment]
@plastbox @agenthunt is any of you planning on making the changes and merging ?
The attachement feature is exactly what I need =)

**Comment by agenthunt** [comment]
I can,  but am waiting for answers/updates from @plastbox on this PR.

**Comment by plastbox** [comment]
Dang, I need to pay better attention to my notifications! Sorry..

I can see if I can't just find the time to update the example and README, if this is still an issue.

**Comment by agenthunt** [comment]
Closing this for now as it is outdated. Thanks.

**Pull request closed without merging**
